### ISSUE TITLE
Euphonic Calculations: Use pylint suggestions to improve code quality

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#103]
As a maintainer of Euphonic, where appropriate, I want my code to have no logical errors and reduced style errors.

Acceptance criteria:

- Pylint warnings have been reduced
- Pylint has been customised to remove innappropriate suggestions
- Python code has been improved to match appropriate suggestions

**Comment by rebeccafair** [comment]
Euphonic now uses Codacy on PRs to alert us to style issues
