### ISSUE TITLE
Euphonic Calculations: Python unit tests: increase code coverage

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#107]
As a maintainer of Euphonic, I would like my unit tests to cover as much of the code as possible.

Acceptance criteria:

- Define a significant increase in code coverage
- A significant increase in coverage is achieved
- Tests are good quality and do not aim to just increase coverage but adequately test any weak areas in the system

**Comment by rebeccafair** [comment]
This has been addressed by https://github.com/pace-neutrons/Euphonic/issues/80
