### ISSUE TITLE
Euphonic Calculations: Python test refactoring

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#108]
As a maintainer of Euphonic, I would like my unit tests to match unit test best practices.

Acceptance criteria:

- Unit tests are not influenced by external factors
- Tests that are not true unit tests are split into a separate testing component or refactored to become true unit tests to prevent loss of code coverage

Notes:

- This may include testing C from Python being moved to an "integration testing" component
- This may include increased mocking

**Comment by stfc-lam** [comment]
Document completed - needs reviewing.

**Comment by rebeccafair** [comment]
This has been addressed by https://github.com/pace-neutrons/Euphonic/issues/80
