### ISSUE TITLE
Euphonic Calculations: Pint testing use

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#109]
As a maintainer of Euphonic, I would like to not need to convert between magnitudes to test with Numpy. 

Acceptance criteria:

- There are no tests which convert to a magnitude for testing with Numpy

Notes:

- This can be achieved using Pint's testing suite

**Comment by rebeccafair** [comment]
No longer planned, but sort of related to https://github.com/pace-neutrons/Euphonic/issues/175
