### ISSUE TITLE
Euphonic Calculations: C extension testing strategy

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#110]
As a maintainer of the Euphonic package, I would like the C extension to be adequately tested, for this a testing strategy should be defined to test this extension.

Acceptance criteria:

- Testing strategy is defined and documented
- Appropriate tools, techniques and processes are put in place to support the easy implementation of testing strategy
- An initial set of tests have been created to meet the strategy
- Relevant further testing is spun out into new tickets

**Comment by rebeccafair** [comment]
As the C extension is only accessible via Python, it is sufficient to test it via the Python interface, so a separate testing strategy for C does not need to be developed.
