### ISSUE TITLE
Euphonic Calculations: Emails on Jenkins failure

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#114]
As a maintainer of Euphonic, I would like to be emailed when a commit I have made results in a failure if a jenkins pipeline.

Acceptance criteria:

- On failure of the pipeline, an email should be sent out to the relevant people

**Comment by rebeccafair** [comment]
Closed by https://github.com/pace-neutrons/Euphonic/pull/58
