### ISSUE TITLE
Explore methods for powder-averaging with arbitary q-points

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Pace-Project-Plan#115]
Blocking #88

Background: https://github.com/pace-neutrons/pace-developers/blob/master/euphonic/design/05_powder_averaging_discussion.md

A principle advantage of sampling at random **q**-points is that the data is not confined to a discrete set of mod(*q*) values; we can vary the mod(*q*) bins after sampling and obtain the binned spherical averages. However, there is not a unique way of calculating the average value in a q-bin. Do we

- weight contributions by how far they are from other samples?
- interpolate from neighbouring points (which may lie outside the bin)?
- form a mesh and use tetrahedron integration, or use some other scheme?

**Comment by stfc-lam** [comment]
on hold

**Comment by cmarooney-stfc** [comment]
@ajjackson Hi Adam, noticing that this ticket is on hold. Could you add a brief description of the block please thanks Chris

**Comment by ajjackson** [comment]
There is no technical block on this; other approaches were found to be reasonably productive and other work has taken a higher priority. This is still an interesting approach that may have some value, especially in the context of a "smart" adaptive scheme.
