### ISSUE TITLE
Euphonic Calculations: Phonopy Gateway

### ISSUE THREAD

**Issue by stfc-lam** [pace-neutrons/Pace-Project-Plan#12]
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/36
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/37
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/38
- [x] #81 
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/39
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/43
- [x] https://github.com/pace-neutrons/Pace-Project-Plan/issues/44
- [x] #69 
- [x] #75 
- [x] #76 
- [x] #100 
- [x] #101

**Comment by rebeccafair** [comment]
Completed and merged into Euphonic master. See [this commit](https://github.com/pace-neutrons/Euphonic/commit/770eab9a7887437779f5085db34305e28652df88)
