### ISSUE TITLE
Manage reference data in Euphonic

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Pace-Project-Plan#136]
Some reference data should be shipped with Euphonic in order to make effective use of its tools. The immediate example is the provision of elemental neutron scattering lengths as required for the calculation of scattering intensity.

A possible implementation is provided in https://github.com/pace-neutrons/Euphonic/pull/79

This blocks #85 which currently depends on the above PR.

In that approach, I have provided elemental data as a JSON file for each property rather than combining multiple properties into tables. Data is then accessed by specifying a combination of "label" and "prop", where "label" identifies a source/collection of data while "prop" identifies the specific property (e.g. coherent scattering cross-section). A simple pattern is also established for the inclusion of unit and citation metadata in the files.

The idea of this system is that users would generally specify the preferred data _source_, while the function accessing the data is likely to be opinionated about what _prop_ is acceptable. (e.g. allowing coherent or incoherent scattering length, but not any derived cross-section data.)

Better names are urgently needed and under discussion in the PR linked above.

Likely interested parties: @rebeccafair  @mducle

**Comment by mducle** [comment]
Hmmm... if "label" is a source or collection, shouldn't it be `source` or `collection` instead? 

What about the database-ish term `entity` for "prop"?

**Comment by ajjackson** [comment]
(Response in https://github.com/pace-neutrons/Euphonic/pull/79 )
