### ISSUE TITLE
Brille: interpolating SpinW structure factors

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Pace-Project-Plan#137]
Whilst working on #134, it was found that using Brille to interpolate the magnon Hamiltonian matrix *eigenvectors*, calculating the spin-spin correlation function from this and then calculating the neutron structure factors from the spin-spin correlation function produces accurate results in all cases tested.

However, this gives only a factor of ~2x speed up compared to the pure SpinW calculation (for small-medium sized systems [matrices]). A much greater speedup can be obtained by skipping the eigenvectors and interpolating the spin-spin correlation tensor directly. However, it was found that this produces inaccurate results in several test cases.

The reason for this inaccuracy (that is the structure factors calculated from the interpolated spin-spin correlation tensor is significantly different from the structure factors calculated directly by SpinW) is uncertain at present.

This issue is to explore why interpolating the spin-spin correlation functions is not accurate in all cases.

There are a couple of possible culprits:

1. There is a phase factor similar to the Gamma transformation which is required for phonon calculations.
2. The calculation doesn't take into account all the necessary *magnetic* symmetry or perhaps uses addition symmetry operations not present in the magnetic structure. The user input is to give the structural spacegroup, atomic coordinates and magnetic structure but at present Brille only uses the symmetry associated with the structural spacegroup; this may have symmetry operations which are not present in the magnetic structure (and hence in the magnetic excitations). Brille may thus need to take into account the (input) magnetic structure and to determine on its own the appropriate symmetry elements.

**Comment by rebeccafair** [comment]
Is this covered by https://github.com/brille/brille/issues/43? Can this be closed?
