### ISSUE TITLE
Euphonic: Journal Paper

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#140]
This issue is to keep track of tasks that need to be completed to put together a paper on Euphonic. New tasks will be added as they  arise.

- [x] #152 
- [x] #153 
- [x] #141
- [x] #142 
- [x] #143
- [x] #144
- [x] #145
- [x] #146
- [x] #147 
- [x] #154 
- [x] #155 
- [x] #156 
- [x] #170  
- [x] #157 
- [x] #158 
- [x] #160
- [x] #168 
- [x] #171 
- [x] Anharmonic phonons? (CM - think we agreed to shelve this at the review on 18/5/21)

**Comment by cmarooney-stfc** [comment]
@rebeccafair Hi Becky, not strictly for this ticket, but looking at the current sprint, you are doing a paper task on the validation & theory section - investigation into dw convergence. Could you say which of the above tickets this refers to? thanks Chris

**Comment by rebeccafair** [comment]
There wasn't specifically a ticket as it was slightly open-ended investigation, but I've created one #160

**Comment by cmarooney-stfc** [comment]
Thanks Becky, much appreciated.

Could I also check that the 2 issues you have planned for the current sprint are Euphonic one 116 (which is actually David’s)  and 118 – the titles look correct unlike the ones on the project plan.

It would be good to know what you think about having 2 different numbering schemes. It would be easier to have a single scheme for the sprint reviews, but appreciating that you will want to track the Euphonic project separately. What do you think is the best way for combining these goals?

Thanks again
Chris

**Comment by rebeccafair** [comment]
I can confirm issues 116 and 118 refer to the ones in the Euphonic repository.

I would prefer to keep specific tasks that involve purely Euphonic code development in Euphonic issues, as once we start to get more external users it may be useful for them to be able to see what new features are being worked on, and avoid duplicating issues/feature requests. Other more general/longer term PACE tasks can go in the Pace-Project-Plan. One suggestion for handling the issue numbers is on the project board any pure number e.g. #116 refers to the issue in Pace-Project-Plan, whereas the repository name + number (no spaces) refers to a specific repository e.g. [Euphonic#116](https://github.com/pace-neutrons/Euphonic/issues/116). Could that be a sensible system?

**Comment by rebeccafair** [comment]
Paper has been submitted!
