### ISSUE TITLE
Euphonic: Journal Paper: Experimental Data Comparison

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#145]
We have experimental and initial simulated 2D cuts for Nb, quartz and LZO but need to include a more quantitative comparison.

- [x] Create publication quality 2D simulated cuts (correct Euphonic inputs, scaling, background?)
- [x] Create 1D cuts of experimental and simulated data for quantitative comparison
- [x] Draft 'Experimental Data Comparison' section for paper
- [ ] Create comparison scripts for 1D cuts
- [ ] Add results (2d, 1d cuts and the scripts used to produce them, and the comparison scripts) to https://github.com/pace-neutrons/euphonic-validation

Sub-issue of #140

**Comment by davidvoneshen** [comment]
I can produce a bunch of nice 1D cuts. I feel like it is probably a waste of your time to then take them and generate some simulated cuts then have to come back to me etc etc. If I put up an example cut, you put in an example to generate the theory then I can play around to generate some decent figures and save you a whole bunch of work (and probably generate relatively little extra for me). Do we have the resolution convolution ready at the moment?

**Comment by rebeccafair** [comment]
One thing we also need to do is create 'publication quality' 2D simulations to show some nice visualisation in addition to the 1D cuts (task 1), are the quick ones I've shown before good enough or do we need to be more careful about broadening, add any backgrounds etc.? I wouldn't know how to do this myself...

For the 1D cuts what you suggested would work, I have no idea how to do the resolution convolution though and how much realistically we could do, which is why I've just been using the plain Gaussian broadening until now. We'd need to ask Toby/Greg.

**Comment by davidvoneshen** [comment]
So, for the 2D cuts. Backgrounds, I would hope we will get away without it. There will be some Al phonons in there but it should be small compared to the scatter from the sample. We should probably be careful about how we broaden the data. Here, like the 1D cuts this is something I can probably help with.

It depends how simple we go.

Option 1: Assume that the instrument resolution is constant with energy transfer. Nice and easy. We can get the width from the elastic line. It is wrong but maybe no-one will notice (this is how I have traditionally produced my data)

Option 2: Get the width for a particular energy from pychop. This is a package within mantid and we can pull a FWHM out very easily. It might slow us down quite a lot though

Option 3: Lets hope we don't get here but we could use tobyfit. However this is really an end goal and if we have to use it we will be here till Christmas. We will also need toby/greg to help us out.

I guess lets start with option 1 and see how it looks. We will need to be consistent though.

David

**Comment by rebeccafair** [comment]
Ok, so what's the next step? I could put up the simulated 2D cuts with no broadening, would you be able to take your 1D cuts and apply any broadening from those?

**Comment by rebeccafair** [comment]
Paper has been submitted!
