### ISSUE TITLE
Euphonic: Journal Paper: Powder Experimental Data Comparison

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#146]
Support for powder in Euphonic is still in early stages, but the following are some very rough tasks if we are in a position to include it in the paper:

- [x] Decide on material to use
- [x] Create Horace cuts
- [x] Compare cuts to Euphonic simulated data as in #145
- [x] Draft powder experimental data comparison section for paper

Sub-issue of #140, depends on #85 being completed and comparing well with experimental data

**Comment by ajjackson** [comment]
David has kindly provided me with some reference plots for a few simple crystals already: Al, Si and Zn. These were "borrowed" from the neutron training school materials. I think the next tasks, which should be added to the checklist, are for me to
- compute or locate force constants data for those materials
- use Euphonic to get get well-converged powder-average spectra

**Comment by ajjackson** [comment]
With the progress on #161 , this silicon case is looking quite nice :-)

![si-coherent-powder-sim](https://user-images.githubusercontent.com/2511383/108854409-bdf46780-75df-11eb-8899-606512f8493a.png)
