### ISSUE TITLE
Brille/SpinW refactor

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Pace-Project-Plan#149]
Brille is mostly written in C++ and currently has two interfaces: `brillem` for Matlab and `brille` and `brilleu` for Python. In fact in addition to a generic interface, these modules (`brillem` and `brilleu`) have specialised interfaces for SpinW and Euphonic, respectively.

We've now decide that these specialist implementations should be moved into the respective codes instead.

This issue is to move the code in `brillem` into `spinw`, leaving a much more basic generic interface between Matlab and Brille. The generic interface will not necessarily be useful to end-users but at least would serve as a functional example for users interested in interfacing their codes to Brille.

**Comment by rebeccafair** [comment]
I think this is now covered by https://github.com/SpinW/spinw/issues/49 in SpinW, correct? If so can I close this issue?
