### ISSUE TITLE
Euphonic: powder-averaging CLI tool

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Pace-Project-Plan#161]
Create a CLI tool with a similar interface to the DOS and dispersion scripts, that

- reads force constants data
- performs numerical powder averaging over a range of q values
- provides user options to control the sampling range and density
- implements a reasonable default strategy
- presents/saves publication-quality spectral plots of S(|q|, w)

**Comment by rebeccafair** [comment]
This was added in https://github.com/pace-neutrons/Euphonic/commit/761752c647709343ec3b9e32015a76924278c7c3 and is available from Euphonic v0.5.0
