### ISSUE TITLE
Euphonic: profile performance of powder-averaging scripts

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Pace-Project-Plan#162]
While working on #116 it was noted that examples for sensitivity analysis were taking a long time to compute. In some cases memory-swapping occurred, bringing progress to a crawl.

- Ensure that the user-facing tool #161 is making effective use of Euphonic's tools
- Check that the bottleneck for large calculations is where it "should" be (i.e. interpolating phonon modes and/or computing S)
- Consider where would be best to "chunk" the sampling to limit memory requirements.

**Comment by rebeccafair** [comment]
Initial investigation has shown that Euphonic does not easily enable optimum parallelism settings when running CLI scripts (by default only the serial Python version of phonon interpolation is used, even though a much faster C/OpenMP version exists). This will be addressed in [Euphonic#128](https://github.com/pace-neutrons/Euphonic/issues/128) and once completed further profiling should be done

**Comment by ajjackson** [comment]
The other thing that came out of this investigation should be simple to fix; the C extensions were not being used by default. I can change the CLI scripts to manage this, but as discussed in https://github.com/pace-neutrons/Euphonic/issues/128 it does also make sense to tweak that default behaviour.

**Comment by ajjackson** [comment]
With C extensions and multithreading I was able to generate this on my Ivy Bridge i7 Desktop in about 2:15. That seems acceptable!

![Figure_1](https://user-images.githubusercontent.com/2511383/108835137-f20f5e80-75c6-11eb-880c-0a102c57059c.png)

**Comment by ajjackson** [comment]
Timing data for a slightly smaller test:
| threads | time |
|-----------|--------|
|   1        | 1:05  |
|   2       |  0:45  |
|   4       |  0:37  |
|   8      | 0:33    |

So it's not linear-scaling in this case, but hyper-threading works great!

(Memory usage could be an issue for larger tests...)

**Comment by rebeccafair** [comment]
The issue of not using the C extension by default was fixed in in https://github.com/pace-neutrons/Euphonic/commit/6696045281af87e6009fdf74f19e9ae7c4894dfc and is available since Euphonic v0.5.0. Closing unless there is immediate need for further speedup.
