### ISSUE TITLE
Euphonic: implement and test effect of radial jitter in powder-averaging

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Pace-Project-Plan#163]
So far powder-averaging is implemented in constant-radius shells, but the results are collected into histogram bins. It is likely that sampling would be improved by sampling a range of radii within the each |q| bin. Either

- Implement this feature
- Consider setting default behaviour

or

- Demonstrate that it is not helpful.

**Comment by rebeccafair** [comment]
Duplicate of https://github.com/pace-neutrons/Euphonic/issues/145?

**Comment by ajjackson** [comment]
It's near enough. Given that there is not any interesting discussion/details here it seems cleanest to close it and let everything happen on the other Issue.
