### ISSUE TITLE
Optimisation of adaptive broadening

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Pace-Project-Plan#174]
Duplicate of existing Euphonic Issue https://github.com/pace-neutrons/Euphonic/issues/135 

Adaptive broadening can be very slow due to the evaluation of N (somewhat long-ranged) Gaussian functions. At present this overwhelms the performance benefit of reduced DOS sampling. Out-of-the-box convolution functions are only suitable for a fixed-width kernel, as used in typical image-broadening applications. Adaptive broadening applies a different width to every data point.

A related problem is the application of an energy/q-dependent instrumental broadening function. In Abins, a novel method was implemented which interpolated between multiple fixed-width convolutions.
https://docs.mantidproject.org/nightly/concepts/AbinsInterpolatedBroadening.html

A project has been created to refine this method and apply a related broadening scheme for adaptive DOS spectra in Euphonic. Further applications may be considered from there.

- [ ] Characterise existing methods
- [ ] Develop/prototype a modified interpolation method. (Abins method relies on a smooth energy/sigma relation which is not guaranteed for adaptive PDOS broadening.)
- [ ] Explore bin-width / anti-aliasing optimisation
- [ ] Implement optimised broadening in Euphonic codebase
- [ ] Consider further extensions and applications of the method

**Comment by rebeccafair** [comment]
Closed by https://github.com/pace-neutrons/Euphonic/pull/197
