### ISSUE TITLE
Euphonic Calculations: Testing

### ISSUE THREAD

**Issue by stfc-lam** [pace-neutrons/Pace-Project-Plan#18]
Ensure Euphonic tests are consistent, robust and cover most use cases

Initial set of tasks (to be added to from https://github.com/users/JamesKingWork/projects/1)

- [x] #89 
- [x] #90
- [x] #91
- [x] #92
- [x] #93
- [x] #96 
- [x] #95
- [x] #99
- [x] #97
- [x] #98
- [x] #102
- [x] #103
- [x] #104
- [x] #105
- [x] #106
- [x] #107
- [x] #108 
- [x] #109
- [x] #110
- [x] #111
- [x] #127

**Comment by JamesKingWork** [comment]
- [ ] #89 
- [ ] #90
- [ ] #91
- [ ] #92
- [ ] #93

**Comment by rebeccafair** [comment]
Completed
