### ISSUE TITLE
Euphonic Calculations: Performance Optimisation: user experience: automate DW convergance

### ISSUE THREAD

**Issue by stfc-lam** [pace-neutrons/Pace-Project-Plan#20]

**Comment by rebeccafair** [comment]
Partially addressed in https://github.com/pace-neutrons/Euphonic/pull/127 as `euphonic.crystal.Crystal.get_mp_grid_spec` can now generate a sensible MP grid from a reciprocal spacing. Further work on this not a priority.

**Comment by ajjackson** [comment]
I'm not sure if we have an issue for this yet but I am quite interested in automatic q-point convergence of DOS etc. and in principle it is the same problem. I may be able to get some help with that in the New Year as part of a graduate project.

I agree that for the purposes of DW what we have is sufficient and this issue can be closed.
