### ISSUE TITLE
User Python and C++ codes: Interface to framework/Build Python framework

### ISSUE THREAD

**Issue by stfc-lam** [pace-neutrons/Pace-Project-Plan#29]

**Comment by cmarooney-stfc** [comment]
@mducle Hi Duc - not certain if this is in yours or Becky's province. Could you let me know who should be going forward with this? thanks CHris

**Comment by mducle** [comment]
@cmarooney-stfc Not sure what this is meant by this issue. I think it can be closed in any case:

If it refers to documentation, that's already covered either by PR pace-neutrons/pace-developers#8 or pace-neutrons/pace-developers#10. The relevant docs are:

[User API design](https://github.com/pace-neutrons/pace-developers/blob/master/optimisation/design/Third_Party_API_Design.md)
[Python framework design](https://github.com/pace-neutrons/pace-developers/blob/master/python_interface/design/01_pace_python_high_level_discussion.md)

If it refers to implementation, then the code is already in [pace-neutrons/pace-python](https://github.com/pace-neutrons/pace-python)

**Comment by mducle** [comment]
Also now covered by [user documentation in Horace](https://pace-neutrons.github.io/Horace/v3.6.2/user_guide/Interfacing_with_other_programs.html).
