### ISSUE TITLE
Euphonic Calculations: Phonopy Gateway: Loader logic

### ISSUE THREAD

**Issue by pjcon** [pace-neutrons/Pace-Project-Plan#36]
Simplify loader logic and ensure only required files are read (e.g. does PhononData require phonopy.yaml to be read?)

Sub issue of https://github.com/pace-neutrons/Pace-Project-Plan/issues/12

**Comment by rebeccafair** [comment]
Completed in work on [this branch](https://github.com/pace-neutrons/Euphonic/commits/8_phonopy_interface)
