### ISSUE TITLE
Euphonic Calculations: Phonopy Gateway: Valid test data formats

### ISSUE THREAD

**Issue by pjcon** [pace-neutrons/Pace-Project-Plan#39]
Generate array of valid Phonopy output files representing range of likely data states. Include makefiles to automatically run phonopy to generate these files.

Sub issue of https://github.com/pace-neutrons/Pace-Project-Plan/issues/12

**Comment by rebeccafair** [comment]
After comparison with NaCl CASTEP calculations (#79) we can say the Phonopy test data is valid and will form the basis for unit tests
