### ISSUE TITLE
Euphonic Calculations: Phonopy Gateway: Force constants readers

### ISSUE THREAD

**Issue by pjcon** [pace-neutrons/Pace-Project-Plan#40]
Manage the range of shapes and data formats for force constants with separate readers.

**Comment by cmarooney-stfc** [comment]
@rebeccafair Hi Becky, Noticing that this one has ended up assigned to someone who may not be on the project any more. What's the best way of updating this ticket? thanks Chris

**Comment by rebeccafair** [comment]
Oh, this one was completed ages ago by https://github.com/pace-neutrons/Euphonic/pull/53, so I'll close this ticket.
