### ISSUE TITLE
Euphonic Calculations: Phonopy Gateway: Phonopy PR

### ISSUE THREAD

**Issue by pjcon** [pace-neutrons/Pace-Project-Plan#42]
Update Phonopy Documentation, unit tests, config file reader, and discuss conformity to Phonopy standard.

Fork of Phonopy with edits:
https://github.com/pjcon/phonopy/tree/ft-add-output-flags

**Comment by rebeccafair** [comment]
Closed by https://github.com/phonopy/phonopy/pull/108
