### ISSUE TITLE
Euphonic Calculations: Phonopy Gateway: Unit tests

### ISSUE THREAD

**Issue by pjcon** [pace-neutrons/Pace-Project-Plan#43]
Update unit tests for Phonopy data loading, ensure pipeline outputs valid results.

Blocking #44 

Sub issue of https://github.com/pace-neutrons/Pace-Project-Plan/issues/12

**Comment by rebeccafair** [comment]
Completed in work on [this branch](https://github.com/pace-neutrons/Euphonic/commits/8_phonopy_interface)
