### ISSUE TITLE
Euphonic Calculations: Phonopy Gateway: Unit test merge

### ISSUE THREAD

**Issue by pjcon** [pace-neutrons/Pace-Project-Plan#44]
Merge unit tests for Phonopy and Castep interpolation data.

Blocked by #43 

Sub issue of https://github.com/pace-neutrons/Pace-Project-Plan/issues/12

**Comment by rebeccafair** [comment]
For now, unit tests of Phonopy and CASTEP will be kept separate, even if this means some duplicated code. There is a project to refactor the testing framework in Euphonic (#18) which will cover this ticket.
