### ISSUE TITLE
Euphonic Calculations: Parallelisation: Investigate memory usage

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#52]
The current C/OpenMP implementation segfaults when performing calculations over 50,000 q-points for Ammonium Sulphate (60 atoms). This didn't happen with the original Python multiprocessing implementation. Need to investigate whether this due to a memory leak or whether Python has just cleverly handled the memory usage in the Python multiprocessing case.

**Comment by cmarooney-stfc** [comment]
@rebeccafair Hi Becky, Just looking through the project board - noticing this has been uninvestigated (or at least not reported here) for a long time. Can we do something about it? Thanks Chris

**Comment by rebeccafair** [comment]
I never actually got round to investigating this more closely. This C/OpenMP implementation has been in use for a while since then and hasn't shown any obvious signs of memory leaks or otherwise worrying behaviour. This is quite a high-stress test case but there's no specific requirement for it to work at the moment, I was just testing the limits of what could be done.

I've got other higher priority things to work on now so maybe this should be closed (or otherwise parked) until there is an actual user case which requires calculations for this many q-points with systems of this size, as it seems at this point this is an optimisation rather than a bug.

**Comment by rebeccafair** [comment]
Closing unless this resurfaces.
