### ISSUE TITLE
Euphonic Calculations: Parallelisation: Profile C code

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#66]
Performance is improved upon the Python implementation, but it could be worth profiling the C code to determine if there are any places we could get noticeable improvements.

**Comment by cmarooney-stfc** [comment]
@rebeccafair Hi Becky - this ticket looks a bit orphaned - not even in the project backlog. Should we progress with this, or is it now not needed? Thanks Chris

**Comment by rebeccafair** [comment]
This is sort of the same state as #52, it might be nice if we could squeeze some more performance out of the C code, but until there's a specific use case there's a long list of more urgent work. I guess it depends on how we want to handle such tickets? Maybe they should be closed?

**Comment by rebeccafair** [comment]
Not currently a priority, closing for now.
