### ISSUE TITLE
Python interface ("pyHorace") design document

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Pace-Project-Plan#78]
We need a preliminary design document for the python interface to drive PACE. 

This should concentrate on the most likely implementation which is that the main `Horace` and `Herbert` code will stay in Matlab/`mex`, and only be accessible as a compiled library.

The alternative - that `Horace` and `Herbert` should be ported to Python/C++ should be considered but is likely not to be chosen.

**Comment by stfc-lam** [comment]
Toby to review
