### ISSUE TITLE
Euphonic Calculations: Validation: Large .sqw file storage

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#80]
For both Euphonic and Horace testing/validation the original .sqw files, cuts and the scripts used to create them need to be stored somewhere. These files are several GB and too large for Git LFS. Using a similar model to Mantid for large file storage would probably be appropriate (ask Martyn Gigg). As for access to resources there are several options in that could be explored:

- Use existing server (e.g. one used to Horace docs? Make use of Mantid infrastructure?)
- Use SCD cloud machines (these could be made easily accessible, but long term storage could be an issue)
- Investigate use of SCD RIG/Tier1 infrastructure (Ask Nick Hill)

Sub issue of #27

**Comment by ajjackson** [comment]
Am I right in thinking that the semi-consensus in this week's meeting was for a dedicated FTP server?

It's worth learning from how Mantid handles this: http://developer.mantidproject.org/DataFilesForTesting.html
The Mantid test framework uses a scheme in which named/version-controlled files contain an MD5 checksum of the actual (potentially large) data file, and the data files are stored in another directory and named by their MD5 sum. There is some logic in the test framework and build process to make these files available when called by name in the tests, and to download any *missing* files from the FTP server when the tests are *built* (using Cmake).

It's a bit complicated but has the advantages that a) version control gives some information about which version of the file is being used and b) files can safely be cached locally without becoming stale, limiting the network/server demands. I wonder if we can develop a procedure for PACE that is about 20% as complicated for 80% of the benefits. (We will not need so many data files, or to update them so often.)

**Comment by mducle** [comment]
I think part of the complications for Mantid is that they need cater for developers from 4 or 5 different facilities in as many countries (and each facility hosts some of the Jenkin agents so the automated builds are also not centralised) so they had to have a publicly accessible server for test data. 

For us, if we use the Storage Area Network which Lamar suggested, this could be mounted by the Jenkins agents (or local developer machines) directly as a network drive so we _should_ not need to download / cache anything... but maybe we might still want that ability (e.g. if you want to download some data to a laptop to be able to develop remotely). We could still implement the MD5-hash-as-file-name scheme that Mantid has to have version control of the test data files in the main repository (and leave the test file server unversioned same as Mantid).

Alternatively, git large file storage (`git-lfs`) in principle does the same thing "transparently" (it stores a text pointer to a file on a remote server, and then caches this after downloading it) but needs a (https) server to act as the remote object store. Github provides one but it's limited to 1GB of storage and 1GB/month of bandwidth with a free account. (We can pay for extras in units of 50GB storage / 50GB/mo bandwidth for $5, but this might get expensive quite quickly). The alternative is to setup our own `git-lfs` object store server but this might also be costly in workload terms...

**Comment by rebeccafair** [comment]
It has been decided to use SAN storage for large file storage across PACE. See https://github.com/pace-neutrons/Horace/issues/141
