### ISSUE TITLE
Euphonic Calculations: Testing: Linting and style checking of Python in CI

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#91]
As a maintainer of Euphonic, I would like my code to be linted on the CI to ensure any code changes do not contain logical errors and are not contrary to style guidelines.

Acceptance criteria:

- Codebase contains pylint configuration matching Euphonic style guidelines
- Jenkinsfile has "Static Code Analysis" stage where pylint is run against python files in the codebase using the pylint configuration
- Outcome of linting is displayed in an appropriate place on Jenkins and/or GitHub

**Comment by ajjackson** [comment]
I wonder if it is viable at this stage to include mypy in the linting. Some whitelisting would seem inevitable given the current level of support for numpy etc. but it would be great to see the internal classes in our function signatures.

**Comment by JamesKingWork** [comment]
> I wonder if it is viable at this stage to include mypy in the linting. Some whitelisting would seem inevitable given the current level of support for numpy etc. but it would be great to see the internal classes in our function signatures.

I think I will spin this out into another ticket as it requires some more thought and would be a decent amount of scope creep.
