### ISSUE TITLE
Euphonic Calculations: Testing: Python code coverage

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#93]
As a maintainer of Euphonic, I would like to know how much of my python code my tests cover.

Acceptance criteria:

- Code coverage is checked in CI
- Code coverage values are displayed in Jenkins

**Comment by ajjackson** [comment]
Code coverage is quite susceptible to https://en.wikipedia.org/wiki/Goodhart%27s_law as it is easy to write high-coverage low-quality tests. Automatic coverage checks are great for information purposes, but we should not set coverage level as a pass/fail criterion for pull requests.

**Comment by JamesKingWork** [comment]
> Code coverage is quite susceptible to https://en.wikipedia.org/wiki/Goodhart%27s_law as it is easy to write high-coverage low-quality tests. Automatic coverage checks are great for information purposes, but we should not set coverage level as a pass/fail criterion for pull requests.

Yes, I absolutely agree, this is just for information purposes to direct us to areas which have weak amounts of testing.
