### ISSUE TITLE
Euphonic Calculations: Script testing

### ISSUE THREAD

**Issue by JamesKingWork** [pace-neutrons/Pace-Project-Plan#98]
As a maintainer of the Euphonic package, I would like the following scripts adequately tested:
- dispersion.py
- dos.py
- optimise_eta.py

Acceptance criteria:

- Testing strategy is defined and documented
- Testing tools, techniques and processes are put in place to support strategy
- An initial set of tests have been created to meet the strategy
- Relevant further testing is spun out into new tickets

Notes:

- All testing has been done as part of this ticket so no new tickets have been created

**Comment by rebeccafair** [comment]
Closed by https://github.com/pace-neutrons/Euphonic/pull/55
